[project]
name = "questiondump"
version = "0.1.0"
description = "FxLifeSheet question dump utility"
requires-python = ">=3.8"
dependencies = [
    "psycopg2-binary>=2.9.0",
    "requests>=2.25.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"