name: ci
on:
  push:
    branches:
      - 'master'
      - 'nginx-deploy'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        working-directory: ./telegram_bot
        with:
          push: true
          tags: dementor/matrix-telegram:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        working-directory: ./viz
        with:
          push: true
          tags: dementor/matrix-viz:latest
