name: ci
on:
  push:
    branches:
      - 'master'
      - 'nginx-deploy'
jobs:
  build-and-push-telegram:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push telegram
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:telegram_bot"
          push: true
          tags: dementor/matrix-telegram:latest
  build-and-push-viz:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push viz
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:viz"
          push: true
          tags: dementor/matrix-viz:latest
