name: ci
on:
  push:
    branches:
      - 'master'
      - 'nginx-deploy'
jobs:
  build-and-push-telegram:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./telegram_bot
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push telegram
        uses: docker/build-push-action@v3
        run:
        with:
          push: true
          tags: dementor/matrix-telegram:latest
  build-and-push-viz:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./viz
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push viz
        uses: docker/build-push-action@v3
        run:
          working-directory: ./viz
        with:
          push: true
          tags: dementor/matrix-viz:latest
